### ISSUE TITLE
Code for generating the figures

### ISSUE THREAD

**Issue by felixhorger** [BRAIN-TO/GIRFReco.jl#8]
Comments on [this file](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/paper/generate_fig_2.jl):
- The name of the file says figure 2, but in the code it says [figure 3](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/paper/generate_fig_2.jl#L2C1-L10C3)
- There are absolute paths specific to the author's computer [here](https://github.com/BRAIN-TO/GIRFReco.jl/blob/9f5b4b98625a5aea1e87d77ca5505ed42ea13c10/paper/generate_fig_2.jl#L25C1-L29C97)
- Pdfs are generated, but then the `figs/` folder includes pngs? See [this issue](https://github.com/BRAIN-TO/GIRFReco.jl/issues/7)

**Comment by alexjaffray** [comment]
@felixhorger The generate_fig_2.jl file wasn't supposed to be included in the submission, this was an oversight on my part. However, it is (for better or worse) submitted, and I can address your comments in order:

- Regarding the figure title and code mismatch, we chose to remove a figure (i.e figure 2 was previously supposed to be figure 3), but I forgot to adjust the figure title in code.
- I will change the code paths to be a placeholder value
- The reason pngs are included rather than pdf is a result of how we did the final step of the figure generation. Running the figure generation code yields a single pdf subfigure of Figure 2, which we then combine and finish externally.  

Would it be appropriate to exclude this file from the submission? I am happy to keep it in its current form with the amendments to address your 1st and second comment, but could remove it as well.

**Comment by felixhorger** [comment]
Hi Alex, keeping it I think is a good idea! If you implement comments 1 & 2 that's good I'd say :)

**Comment by alexjaffray** [comment]
Thanks @felixhorger ! Adding it to my TODO list

**Comment by alexjaffray** [comment]
Completed in e81f4e4.
